In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir("C:/Users/vyshn/Desktop/Data sets")
test = pd.read_excel('Test_dataset.xlsx')

In [3]:
test.head()

City          State   Type  Population [2011]  Popuation [2001]  \
0      Tuensang       Nagaland    T.C            36774.0               NaN   
1  Lakshmeshwar      Karnataka  T.M.C            36754.0               NaN   
2          Zira         Punjab  M.Cl.            36732.0               NaN   
3         Yawal    Maharashtra   M.Cl            36706.0               NaN   
4  Thana Bhawan  Uttar Pradesh   N.P.            36669.0               NaN   

   Sex Ratio  Median Age  Avg Temp     SWM  Toilets Avl  Water Purity  \
0      931.0        23.0      10.0  MEDIUM         94.0         114.0   
1      934.0        25.0      38.0    HIGH         62.0         160.0   
2      883.0        29.0      35.0    HIGH         63.0         105.0   
3      887.0        26.0      31.0    HIGH         60.0         174.0   
4      877.0        28.0      39.0     LOW         92.0         153.0   

    H Index  Female Population  # of hospitals  Foreign Visitors  
0  0.253390            34237.0            17.0            2769.0  
1  0.192555            34328.0            13.0          636502.0  
2  0.887882            32434.0            17.0          242367.0  
3  0.407838            32558.0            11.0         4408916.0  
4  0.324456            32159.0            23.0         3104060.0

In [4]:
train = pd.read_excel('Train_dataset.xlsx')

In [5]:
train.head()

City        State  Type  Population [2011]  Popuation [2001]  \
0     Mumbai  Maharashtra   M.C         12442373.0        11978450.0   
1      Delhi        Delhi   M.C         11007835.0         9879172.0   
2  Bangalore    Karnataka  MPUA          8436675.0         4301326.0   
3  Hyderabad    Telangana  MPUA          6809970.0         3637483.0   
4  Ahmedabad      Gujarat  MPUA          5570585.0         3520085.0   

   Sex Ratio  Median Age  Avg Temp     SWM  Toilets Avl  Water Purity  \
0      878.0        23.0      32.0  MEDIUM        219.0         150.0   
1      858.0        27.0      30.0  MEDIUM        215.0         196.0   
2      936.0        28.0      37.0    HIGH        212.0         102.0   
3      930.0        23.0      31.0  MEDIUM        217.0         118.0   
4      852.0        29.0      25.0     LOW        227.0         109.0   

    H Index  Female Population  # of hospitals  Foreign Visitors  Covid Cases  
0  0.700440         10924403.0           159.0         4408916.0       163115  
1  0.920018          9444722.0           148.0         2379169.0        80188  
2  0.097085          7896728.0           123.0          636502.0       141000  
3  0.827744          6333272.0           110.0          126078.0        55123  
4  0.847941          4746138.0            73.0          284973.0        33204

In [6]:
test.isnull().sum()

City                   0
State                  0
Type                   2
Population [2011]      6
Popuation [2001]     501
Sex Ratio              5
Median Age            13
Avg Temp              14
SWM                    9
Toilets Avl           22
Water Purity          19
H Index               15
Female Population     15
# of hospitals        17
Foreign Visitors      17
dtype: int64

In [7]:
train.isnull().sum()

City                   0
State                  0
Type                   0
Population [2011]     48
Popuation [2001]     492
Sex Ratio             10
Median Age            18
Avg Temp              17
SWM                    4
Toilets Avl           26
Water Purity         158
H Index              140
Female Population    141
# of hospitals        15
Foreign Visitors      90
Covid Cases            0
dtype: int64

In [8]:
train.fillna(train['Population [2011]'].mean(),inplace = True)
train.fillna(train['Popuation [2001]'].mean(),inplace = True)
train.fillna(train['Sex Ratio'].mean(),inplace = True)
train.fillna(train['Median Age'].mean(),inplace = True)
train.fillna(train['Avg Temp'].mean(),inplace = True)
train["SWM"].fillna( method ='ffill', inplace = True)
train.fillna(train['Toilets Avl'].mean(),inplace = True)
train.fillna(train['Water Purity'].mean(),inplace = True)
train.fillna(train['H Index'].mean(),inplace = True)
train.fillna(train['Female Population'].mean(),inplace = True)
train.fillna(train['# of hospitals'].mode(),inplace = True)
train.fillna(train['Foreign Visitors'].mean(),inplace = True)

In [9]:
train.isnull().sum()

City                 0
State                0
Type                 0
Population [2011]    0
Popuation [2001]     0
Sex Ratio            0
Median Age           0
Avg Temp             0
SWM                  0
Toilets Avl          0
Water Purity         0
H Index              0
Female Population    0
# of hospitals       0
Foreign Visitors     0
Covid Cases          0
dtype: int64

In [10]:
train.isnull().any()

City                 False
State                False
Type                 False
Population [2011]    False
Popuation [2001]     False
Sex Ratio            False
Median Age           False
Avg Temp             False
SWM                  False
Toilets Avl          False
Water Purity         False
H Index              False
Female Population    False
# of hospitals       False
Foreign Visitors     False
Covid Cases          False
dtype: bool

In [11]:
train.dtypes

City                  object
State                 object
Type                  object
Population [2011]    float64
Popuation [2001]     float64
Sex Ratio            float64
Median Age           float64
Avg Temp             float64
SWM                   object
Toilets Avl          float64
Water Purity         float64
H Index              float64
Female Population    float64
# of hospitals       float64
Foreign Visitors     float64
Covid Cases            int64
dtype: object

In [12]:
train['SWM'].value_counts()

HIGH                 272
LOW                  260
MEDIUM               251
310283.4167794317      4
Name: SWM, dtype: int64

In [13]:
train.drop(train[train['SWM'] == 310283.4167794317].index, axis=0, inplace = True) 

In [14]:
train['SWM'].value_counts()

HIGH      272
LOW       260
MEDIUM    251
Name: SWM, dtype: int64

In [15]:
train['City'].value_counts()

Aurangabad     3
Ramnagar       3
Tiruppur       2
Miryalaguda    2
Tezpur         2
              ..
Ujhani         1
Parli          1
Raiganj        1
Bodhan         1
Umred          1
Name: City, Length: 768, dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder #Converting categorical values into the numeric 
le = LabelEncoder() 
  
train['City']= le.fit_transform(train['City']) 
train['State']= le.fit_transform(train['State']) 
train['Type']= le.fit_transform(train['Type']) 
train['SWM']= le.fit_transform(train['SWM']) 

In [17]:
train.drop(['Popuation [2001]'], axis='columns', inplace=True)

In [18]:
train.head()

City  State  Type  Population [2011]  Sex Ratio  Median Age  Avg Temp  SWM  \
0   377     16    10         12442373.0      878.0        23.0      32.0    2   
1   135      6    10         11007835.0      858.0        27.0      30.0    2   
2    52     13    16          8436675.0      936.0        28.0      37.0    0   
3   210     28    16          6809970.0      930.0        23.0      31.0    2   
4     3      8    16          5570585.0      852.0        29.0      25.0    1   

   Toilets Avl  Water Purity   H Index  Female Population  # of hospitals  \
0        219.0         150.0  0.700440         10924403.0           159.0   
1        215.0         196.0  0.920018          9444722.0           148.0   
2        212.0         102.0  0.097085          7896728.0           123.0   
3        217.0         118.0  0.827744          6333272.0           110.0   
4        227.0         109.0  0.847941          4746138.0            73.0   

   Foreign Visitors  Covid Cases  
0         4408916.0       163115  
1         2379169.0        80188  
2          636502.0       141000  
3          126078.0        55123  
4          284973.0        33204

In [19]:
train['Covid Cases'].value_counts()

2523    6
2490    5
2208    5
2213    4
2220    4
       ..
9809    1
8783    1
2747    1
8776    1
2291    1
Name: Covid Cases, Length: 639, dtype: int64

In [20]:
test.head()

City          State   Type  Population [2011]  Popuation [2001]  \
0      Tuensang       Nagaland    T.C            36774.0               NaN   
1  Lakshmeshwar      Karnataka  T.M.C            36754.0               NaN   
2          Zira         Punjab  M.Cl.            36732.0               NaN   
3         Yawal    Maharashtra   M.Cl            36706.0               NaN   
4  Thana Bhawan  Uttar Pradesh   N.P.            36669.0               NaN   

   Sex Ratio  Median Age  Avg Temp     SWM  Toilets Avl  Water Purity  \
0      931.0        23.0      10.0  MEDIUM         94.0         114.0   
1      934.0        25.0      38.0    HIGH         62.0         160.0   
2      883.0        29.0      35.0    HIGH         63.0         105.0   
3      887.0        26.0      31.0    HIGH         60.0         174.0   
4      877.0        28.0      39.0     LOW         92.0         153.0   

    H Index  Female Population  # of hospitals  Foreign Visitors  
0  0.253390            34237.0            17.0            2769.0  
1  0.192555            34328.0            13.0          636502.0  
2  0.887882            32434.0            17.0          242367.0  
3  0.407838            32558.0            11.0         4408916.0  
4  0.324456            32159.0            23.0         3104060.0

In [21]:
test.isnull().sum()

City                   0
State                  0
Type                   2
Population [2011]      6
Popuation [2001]     501
Sex Ratio              5
Median Age            13
Avg Temp              14
SWM                    9
Toilets Avl           22
Water Purity          19
H Index               15
Female Population     15
# of hospitals        17
Foreign Visitors      17
dtype: int64

In [23]:
test.fillna(test['Population [2011]'].mean(),inplace = True)
test.fillna(test['Popuation [2001]'].mean(),inplace = True)
test.fillna(test['Sex Ratio'].mean(),inplace = True)
test.fillna(test['Median Age'].mean(),inplace = True)
test.fillna(test['Avg Temp'].mean(),inplace = True)
test["SWM"].fillna( method ='ffill', inplace = True)
test.fillna(test['Toilets Avl'].mean(),inplace = True)
test.fillna(test['Water Purity'].mean(),inplace = True)
test.fillna(test['H Index'].mean(),inplace = True)
test.fillna(test['Female Population'].mean(),inplace = True)
test.fillna(test['# of hospitals'].mode(),inplace = True)
test.fillna(test['Foreign Visitors'].mean(),inplace = True)

In [24]:
test.drop(['Popuation [2001]'], axis='columns', inplace=True)

In [25]:
test.head()

City          State   Type  Population [2011]  Sex Ratio  \
0      Tuensang       Nagaland    T.C            36774.0      931.0   
1  Lakshmeshwar      Karnataka  T.M.C            36754.0      934.0   
2          Zira         Punjab  M.Cl.            36732.0      883.0   
3         Yawal    Maharashtra   M.Cl            36706.0      887.0   
4  Thana Bhawan  Uttar Pradesh   N.P.            36669.0      877.0   

   Median Age  Avg Temp     SWM  Toilets Avl  Water Purity   H Index  \
0        23.0      10.0  MEDIUM         94.0         114.0  0.253390   
1        25.0      38.0    HIGH         62.0         160.0  0.192555   
2        29.0      35.0    HIGH         63.0         105.0  0.887882   
3        26.0      31.0    HIGH         60.0         174.0  0.407838   
4        28.0      39.0     LOW         92.0         153.0  0.324456   

   Female Population  # of hospitals  Foreign Visitors  
0            34237.0            17.0            2769.0  
1            34328.0            13.0          636502.0  
2            32434.0            17.0          242367.0  
3            32558.0            11.0         4408916.0  
4            32159.0            23.0         3104060.0

In [26]:
test['SWM'].value_counts()

LOW                   179
HIGH                  158
MEDIUM                155
24747.468686868688      9
Name: SWM, dtype: int64

In [27]:
test['Type'].value_counts()

M                     119
N.P                    86
M.Cl                   61
T.P                    42
C.T                    41
T.M.C                  22
N.P.P                  19
N.A                    19
M.B                    16
M.C                     8
UA                      8
C.T.                    7
M.Cl.                   6
N.P.                    6
T.C                     6
T.M.C.                  5
T.P.                    4
N.P.P.                  4
N.A.C                   3
G.P                     3
24747.468686868688      2
M.C.                    2
N.T                     2
I.N.A                   1
N.A.C.                  1
T.C.                    1
NP                      1
M&F                     1
G.P.                    1
NAC                     1
CT                      1
M.B.                    1
TP                      1
Name: Type, dtype: int64

In [28]:
test.drop(test[test['SWM'] == 296382.6092023149].index, axis=0, inplace = True) 

In [29]:
test.drop(test[test['SWM'] == 24747.468686868688].index, axis=0, inplace = True) 

In [30]:
test['SWM'].value_counts()

LOW       179
HIGH      158
MEDIUM    155
Name: SWM, dtype: int64

In [31]:
test['Type'].value_counts()

M                     117
N.P                    83
M.Cl                   61
T.P                    41
C.T                    40
T.M.C                  22
N.P.P                  19
N.A                    18
M.B                    16
M.C                     8
UA                      8
C.T.                    7
M.Cl.                   6
N.P.                    6
T.C                     5
T.M.C.                  5
T.P.                    4
N.P.P.                  4
N.A.C                   3
G.P                     3
24747.468686868688      2
M.C.                    2
N.T                     2
I.N.A                   1
N.A.C.                  1
T.C.                    1
NP                      1
M&F                     1
G.P.                    1
NAC                     1
CT                      1
M.B.                    1
TP                      1
Name: Type, dtype: int64

In [32]:
test.drop(test[test['Type'] == 24747.468686868688].index, axis=0, inplace = True) 

In [33]:
test.isnull().sum()

City                 0
State                0
Type                 0
Population [2011]    0
Sex Ratio            0
Median Age           0
Avg Temp             0
SWM                  0
Toilets Avl          0
Water Purity         0
H Index              0
Female Population    0
# of hospitals       0
Foreign Visitors     0
dtype: int64

In [34]:
cities = test['City']

In [35]:
from sklearn.preprocessing import LabelEncoder #Converting categorical values into the numeric 
le = LabelEncoder() 
  
test['City']= le.fit_transform(test['City']) 
test['State']= le.fit_transform(test['State']) 
test['Type']= le.fit_transform(test['Type']) 
test['SWM']= le.fit_transform(test['SWM']) 

In [36]:
X1 = train.iloc[:, :-1].values
y1 = train.iloc[:, -1].values

In [37]:

from sklearn.model_selection import train_test_split

# Splitting dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.3,random_state=109) # 70% training and 30% test

In [38]:
X_train

array([[5.88000000e+02, 3.20000000e+01, 0.00000000e+00, ...,
        1.72386000e+05, 8.30000000e+01, 1.48950000e+06],
       [3.68000000e+02, 8.00000000e+00, 6.00000000e+00, ...,
        4.55820000e+04, 3.00000000e+01, 2.84973000e+05],
       [1.90000000e+01, 1.60000000e+01, 0.00000000e+00, ...,
        2.21237000e+05, 9.90000000e+01, 3.10283417e+05],
       ...,
       [5.26000000e+02, 2.60000000e+01, 3.30000000e+01, ...,
        3.48170000e+04, 1.60000000e+01, 4.68470700e+06],
       [2.82000000e+02, 3.00000000e+01, 0.00000000e+00, ...,
        1.67933000e+05, 6.80000000e+01, 3.10406000e+06],
       [6.57000000e+02, 8.00000000e+00, 0.00000000e+00, ...,
        1.54908000e+05, 9.50000000e+01, 2.84973000e+05]])

In [39]:
test

City  State  Type  Population [2011]  Sex Ratio  Median Age  Avg Temp  \
0     439     19    24       36774.000000      931.0        23.0      10.0   
1      69     12    26       36754.000000      934.0        25.0      38.0   
2     484     21    13       36732.000000      883.0        29.0      35.0   
3     479     15    12       36706.000000      887.0        26.0      31.0   
4     421     26    18       36669.000000      877.0        28.0      39.0   
..    ...    ...   ...                ...        ...         ...       ...   
496   166     27    17        1641.000000      848.0        27.0       7.0   
497    60     27    17        1517.000000      852.0        28.0      12.0   
498    55     27    17         612.000000      853.0        24.0       9.0   
499    42     27    17         110.000000      852.0        27.0       8.0   
500    63     26     0       24747.468687      863.0        24.0      35.0   

     SWM  Toilets Avl  Water Purity   H Index  Female Population  \
0      2         94.0         114.0  0.253390            34237.0   
1      0         62.0         160.0  0.192555            34328.0   
2      0         63.0         105.0  0.887882            32434.0   
3      0         60.0         174.0  0.407838            32558.0   
4      1         92.0         153.0  0.324456            32159.0   
..   ...          ...           ...       ...                ...   
496    2         12.0         181.0  0.316926             1392.0   
497    0         16.0         198.0  0.336852             1292.0   
498    1         19.0         189.0  0.723253              522.0   
499    2         18.0         170.0  0.421061               94.0   
500    0         19.0         149.0  0.154375                0.0   

     # of hospitals  Foreign Visitors  
0              17.0            2769.0  
1              13.0          636502.0  
2              17.0          242367.0  
3              11.0         4408916.0  
4              23.0         3104060.0  
..              ...               ...  
496             4.0          105882.0  
497             6.0          105882.0  
498             6.0          105882.0  
499             8.0          105882.0  
500             6.0         3104060.0  

[490 rows x 14 columns]

In [40]:
test['SWM'].value_counts()

1    179
0    156
2    155
Name: SWM, dtype: int64

# LogisticRegression

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
model = LogisticRegression(max_iter=2000)

In [43]:
model.fit(X_train, y_train)

C:\Users\vyshn\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [44]:
yhat = model.predict(test)

In [45]:
yhat

array([ 2285,  2220,  2069,  2628,  2434,  2220,  2628,  9538,  2220,
        2052,  2490,  2628, 12365,  2648,  2628,  2220,  2220,  2220,
        2220,  2069,  2220,  2052,  1689,  2628,  2052,  2220,  2628,
        2301,  2285,  2976,  2220,  2052,  3702,  2628,  2628,  2132,
        2301,  2052,  2220,  2052,  2628,  2628,  2220,  2976,  2648,
        2220,  2220,  2220,  2220,  2628,  2069,  2069,  2220,  9441,
        2473,  2487,  2188,  2220,  9538,  2628,  2052,  2628,  2473,
        2576,  2220,  2450,  2069,  2196,  2163,  2523,  2523,  2163,
        2450,  9538,  2473,  9179,  2052,  2628,  2052,  2069,  2628,
        2220,  2220,  2220,  2628,  2473,  2976,  9538,  2450,  3734,
        2220,  2220,  2220,  2220,  2450,  2628,  2473,  2628,  2450,
        2487,  2052,  2628,  2628,  2301,  2220,  2628,  3734,  2220,
        2220,  2052,  2628,  2576,  8263,  2628, 10608,  2628,  2285,
        2382,  2052,  2052,  2382,  2220,  9179,  2473, 10933,  2487,
        2628,  2628,

In [46]:
from sklearn.svm import SVR

In [47]:
svm_confirmed = SVR()

In [48]:
svm_confirmed.fit(X_test, y_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [49]:
svm_pred_confirm = svm_confirmed.predict(test)

In [50]:
svm_pred_confirm

array([2567.2974701 , 2568.41605742, 2567.82747403, 2552.31771486,
       2557.65983693, 2568.41630588, 2552.31711895, 2567.58111403,
       2568.41286723, 2567.48695859, 2567.45455539, 2552.31530135,
       2567.29239265, 2567.66747641, 2552.31470444, 2568.41006507,
       2568.40942726, 2568.14691027, 2568.14692147, 2567.80862774,
       2568.40587977, 2567.48524539, 2567.4170841 , 2552.31355967,
       2567.48100037, 2568.40397125, 2552.31934453, 2557.65097108,
       2567.28277643, 2567.89415402, 2568.39789508, 2567.47629623,
       2567.29083046, 2552.31082744, 2552.30950973, 2567.80883576,
       2557.64859169, 2567.47515653, 2568.13524485, 2567.47346466,
       2552.31588226, 2552.30988266, 2568.11029902, 2567.88770911,
       2567.50883014, 2568.13381061, 2568.45650137, 2568.45664935,
       2568.13126241, 2552.30843589, 2567.64975107, 2567.65064988,
       2568.43673503, 2567.42939138, 2567.88125634, 2567.79944733,
       2557.64655072, 2568.4549664 , 2567.56099658, 2552.31428

# KNN Clssifier

In [51]:
#Using KNN Classifier
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [53]:
y_pred = classifier.predict(test)

In [54]:
y_pred

array([145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
       145606, 145606, 145606, 145606, 145606, 145606, 145606, 145606,
      

# Using Guassian Naive Bayes Classifier

In [55]:
from sklearn.naive_bayes import GaussianNB

In [56]:
gnb = GaussianNB()

In [57]:
y_pred = gnb.fit(X_train, y_train).predict(test)
y_pred

array([2473, 2473, 2473, 2523, 2523, 2473, 2523, 2473, 2473, 2523, 2523,
       2523, 2473, 2473, 2523, 2473, 2473, 2473, 2473, 2473, 2473, 2523,
       2473, 2523, 2523, 2473, 2523, 2523, 2473, 2473, 2473, 2523, 2175,
       2523, 2523, 2473, 2523, 2523, 2473, 2523, 2523, 2523, 2473, 2473,
       2473, 2473, 2473, 2473, 2473, 2523, 2473, 2473, 2473, 2473, 2473,
       2473, 2523, 2473, 2473, 2523, 2523, 2523, 2473, 2473, 2473, 2523,
       2473, 2523, 2523, 2523, 2523, 2523, 2523, 2473, 2473, 2473, 2523,
       2523, 2523, 2473, 2523, 2473, 2473, 2473, 2523, 2473, 2473, 2473,
       2523, 2473, 2473, 2473, 2473, 2473, 2523, 2523, 2473, 2523, 2523,
       2473, 2523, 2523, 2523, 2523, 2473, 2523, 2473, 2473, 2473, 2523,
       2523, 2473, 2473, 2523, 2473, 2523, 2473, 2523, 2523, 2523, 2523,
       2473, 2473, 2473, 2473, 2473, 2523, 2523, 2523, 2523, 2473, 2473,
       2473, 2473, 2473, 2473, 2473, 2473, 2473, 2473, 2473, 2523, 2473,
       2473, 2523, 2473, 2473, 2523, 2523, 2473, 25

# Using Ridge

In [58]:
from sklearn.linear_model import Ridge

In [59]:
import numpy as np

In [60]:
n_samples, n_features = 490, 14

In [61]:
rng = np.random.RandomState(0)

In [62]:
y = rng.randn(n_samples)

In [63]:
X = rng.randn(n_samples, n_features)

In [64]:
clf = Ridge(alpha=1.0)
clf.fit(X, y)
Ridge()

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [65]:
a = clf.predict(test)
a

array([ 2056.63478649,  6019.33338563,  3516.13210086, 29485.40210016,
       21346.11000776,  6013.24159777, 29478.8673563 ,  2797.74379543,
        5993.10196822, 11163.37587719, 11312.54642583, 29455.33089375,
        2020.15792243,  3033.34427886, 29436.5977583 ,  5968.44918993,
        5969.88650363,  4609.9088311 ,  4618.04142365,  3427.47048398,
        5942.45975119, 11133.21869255,  2319.83084553, 29416.54062068,
       11118.36616327,  5939.98042357, 31139.59139285, 21257.95923743,
        1956.54239631,  3680.99837379,  5894.55238061, 11080.95129403,
        2537.58339756, 29371.9687336 , 29357.92579466,  3398.9782406 ,
       21216.98310719, 11076.55474667,  4538.86810759, 11067.06601842,
       31079.48811757, 29356.33784016,  4428.90453036,  3631.81035301,
        2519.80926467,  4520.57407188,  7630.21185311,  7637.83992255,
        4510.12768125, 29327.92412845,  2909.59853218,  2920.18253697,
        8009.53539574,  2311.38075161,  3595.92147425,  3358.89750492,
      

In [66]:
Final = pd.DataFrame({'City': cities, 'Corona Cases': np.round(a)})

In [67]:
Final

City  Corona Cases
0        Tuensang        2057.0
1    Lakshmeshwar        6019.0
2            Zira        3516.0
3           Yawal       29485.0
4    Thana Bhawan       21346.0
..            ...           ...
496   Nandaprayag         720.0
497    Kirtinagar         717.0
498     Kedarnath         667.0
499      Gangotri         638.0
500     Kumarganj       20314.0

[490 rows x 2 columns]

In [70]:
Final.to_csv(r'C:\Users\vyshn\Desktop\Data sets\Output-Part(1).csv')